name: MooLib
version: 1.0.2
main: com.otabi.firestar.moolib.MooLibPlugin
commands:
   reloadplugin:
      description: Reloads the specified plugin.
      usage: /<command> <plugin>
loadbefore: [FireworkProjectiles, LeashedPlayers]