name: ${artifactId}
version: ${version}
main: ${groupId}.${artifactId}
commands:
   reloadplugin:
      description: Reloads the specified plugin.
      usage: /<command> <plugin>
loadbefore: [FireworkProjectiles, LeashedPlayers]